# Generated by Django 3.1.7 on 2021-11-03 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0005_useraccount'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAccount',
        ),
    ]
